-- =========================================================
-- CHAMPIONSTORE COMPLETE DATABASE SCHEMA & PERMISSIONS
-- Run this in Supabase SQL Editor
-- =========================================================

-- 1. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    robux INTEGER NOT NULL,
    price NUMERIC NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. STORE SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.store_settings (
    id TEXT PRIMARY KEY DEFAULT 'default',
    store_name TEXT DEFAULT 'ChampionStore_IDN',
    whatsapp_number TEXT DEFAULT '6285828378025',
    whatsapp_url TEXT DEFAULT 'https://wa.me/6285828378025',
    is_store_open BOOLEAN DEFAULT TRUE,
    qris_image_path TEXT DEFAULT '/qris.webp',
    logo_image_path TEXT DEFAULT '/logo.webp',
    banner_image_path TEXT DEFAULT '',
    promo_active BOOLEAN DEFAULT TRUE,
    promo_tag TEXT DEFAULT 'PROMO SPESIAL BULAN INI',
    promo_badge TEXT DEFAULT 'LIMITED STOCK',
    promo_title TEXT DEFAULT 'ROBUX BULAN INI',
    promo_subtitle TEXT DEFAULT 'Top Up Robux Instant, Cepat, Legal, Aman & Bergaransi 100% Uang Kembali!',
    promo_robux_amount INTEGER DEFAULT 2200,
    promo_original_label TEXT DEFAULT '2.000 Robux',
    promo_discount_price NUMERIC DEFAULT 45000,
    promo_end_date TIMESTAMPTZ,
    admin_note TEXT DEFAULT 'Catatan penting untuk tim operasional toko.',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. ORDERS TABLE
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code TEXT UNIQUE NOT NULL,
    product_id BIGINT,
    roblox_username TEXT NOT NULL,
    roblox_user_id TEXT,
    customer_phone TEXT DEFAULT '-',
    robux INTEGER NOT NULL DEFAULT 0,
    price NUMERIC NOT NULL DEFAULT 0,
    payment_method TEXT DEFAULT 'Website',
    payment_status TEXT DEFAULT 'pending',
    order_status TEXT DEFAULT 'pending',
    payment_proof_path TEXT,
    customer_notes TEXT,
    admin_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. BLACKLISTS TABLE
CREATE TABLE IF NOT EXISTS public.blacklists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roblox_username TEXT UNIQUE NOT NULL,
    phone TEXT,
    roblox_user_id TEXT,
    reason TEXT DEFAULT 'Indikasi penipuan atau penyalahgunaan',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TESTIMONIALS TABLE
CREATE TABLE IF NOT EXISTS public.testimonials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    rating INTEGER DEFAULT 5,
    message TEXT NOT NULL,
    image_path TEXT,
    order_code TEXT,
    status TEXT DEFAULT 'approved',
    admin_reply TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. ACTIVITY LOGS TABLE
CREATE TABLE IF NOT EXISTS public.activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,
    details TEXT NOT NULL,
    order_id TEXT,
    user_target TEXT,
    type TEXT DEFAULT 'system',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. CUSTOMERS TABLE
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roblox_username TEXT UNIQUE NOT NULL,
    roblox_id TEXT,
    phone TEXT,
    total_orders INTEGER DEFAULT 0,
    total_spent NUMERIC DEFAULT 0,
    tier TEXT DEFAULT 'Bronze',
    is_blacklisted BOOLEAN DEFAULT FALSE,
    last_order_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================================
-- GRANT PERMISSIONS & ROW LEVEL SECURITY
-- =========================================================
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;

-- Enable RLS & Add Full Access Policies
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all on products" ON public.products;
CREATE POLICY "Allow all on products" ON public.products FOR ALL TO public, anon, authenticated, service_role USING (true) WITH CHECK (true);

ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all on store_settings" ON public.store_settings;
CREATE POLICY "Allow all on store_settings" ON public.store_settings FOR ALL TO public, anon, authenticated, service_role USING (true) WITH CHECK (true);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all on orders" ON public.orders;
CREATE POLICY "Allow all on orders" ON public.orders FOR ALL TO public, anon, authenticated, service_role USING (true) WITH CHECK (true);

ALTER TABLE public.blacklists ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all on blacklists" ON public.blacklists;
CREATE POLICY "Allow all on blacklists" ON public.blacklists FOR ALL TO public, anon, authenticated, service_role USING (true) WITH CHECK (true);

ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all on testimonials" ON public.testimonials;
CREATE POLICY "Allow all on testimonials" ON public.testimonials FOR ALL TO public, anon, authenticated, service_role USING (true) WITH CHECK (true);

ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all on activity_logs" ON public.activity_logs;
CREATE POLICY "Allow all on activity_logs" ON public.activity_logs FOR ALL TO public, anon, authenticated, service_role USING (true) WITH CHECK (true);

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all on customers" ON public.customers;
CREATE POLICY "Allow all on customers" ON public.customers FOR ALL TO public, anon, authenticated, service_role USING (true) WITH CHECK (true);

-- =========================================================
-- STORAGE BUCKETS
-- =========================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('payment-proofs', 'payment-proofs', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Allow public upload payment proofs" ON storage.objects;
CREATE POLICY "Allow public upload payment proofs" ON storage.objects FOR INSERT TO public, anon, authenticated, service_role WITH CHECK (bucket_id = 'payment-proofs');

DROP POLICY IF EXISTS "Allow public view payment proofs" ON storage.objects;
CREATE POLICY "Allow public view payment proofs" ON storage.objects FOR SELECT TO public, anon, authenticated, service_role USING (bucket_id = 'payment-proofs');

-- =========================================================
-- SEED DEFAULT SETTINGS & PRODUCTS
-- =========================================================
INSERT INTO public.store_settings (id, store_name, whatsapp_number, promo_active, promo_robux_amount, promo_discount_price)
VALUES ('default', 'ChampionStore_IDN', '6285828378025', true, 2200, 45000)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.products (name, robux, price, is_active)
VALUES
  ('800 Robux', 800, 105000, true),
  ('1.200 Robux', 1200, 155000, true),
  ('1.700 Robux', 1700, 215000, true),
  ('2.200 Robux (Promo)', 2200, 275000, true),
  ('3.200 Robux', 3200, 395000, true),
  ('5.600 Robux', 5600, 695000, true),
  ('10.000 Robux', 10000, 1190000, true)
ON CONFLICT DO NOTHING;

-- Reload Supabase Schema Cache
NOTIFY pgrst, 'reload schema';
